export const SET_CREATE_TARGET: string = "SET_TARGET";
export const SET_CREATE_TARGET_INITIAL_OPTIONS: string = "SET_INITIAL_OPTIONS";
export const SET_CREATE_TARGET_POSITION: string = "SET_TARGET_POSITION";
